# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Note cards!
email: hello@flyinggrizzly.io
description: > # This Jekyll theme is designed to make flash and note cards easy to use and refer to.
baseurl: ""
url: "http://github.com/flyinggrizzly/note-cards"
twitter_username: flying_grizzly
github_username:  flyinggrizzly

contrib_url: > # Put the URL where people can contribute here.
copyright_owner: Flying Grizzly

# Build settings
markdown: kramdown

exclude:
          - todo.md
